<?php

namespace JustCommunication\FuncBundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class FuncBundle extends Bundle{
    public function build(ContainerBuilder $container):void
    {
        parent::build($container); // TODO: Change the autogenerated stub
        //$container->addCompilerPass(new ExporterRegistrationPass());
    }

    public function getPath(): string
    {
        return dirname(__DIR__);
    }

}